### ISSUE TITLE
Вылет

### ISSUE THREAD

**Issue by viralium** [user95401/MenuMusicToggle#1]
Просто игра не запускается

**Comment by lil2kki** [comment]
минхук есть?

**Comment by viralgmd** [comment]
Да

**Comment by lil2kki** [comment]
попробуй этот билд 
https://github.com/user95401/MenuMusicToggle/releases/download/betas/MenuMusicToggle.dll

**Comment by viralgmd** [comment]
Нет также.

**Comment by lil2kki** [comment]
попробуй установить Windows SDK

**Comment by viralgmd** [comment]
У меня Visual Studio есть соответственно и Windows 10 SDK

**Comment by lil2kki** [comment]
привет, вышла вторая версия мода и у чела которого не работала первая - работает вторая
вот билд второй версии https://github.com/user95401/MenuMusicToggle/releases/download/release/MenuMusicToggle.dll

**Comment by viralgmd** [comment]
![image](https://user-images.githubusercontent.com/129858326/232248196-eb0968a6-9125-4ea8-bb62-5b3af60d20ca.png)
Спс теперь работает!
Кстати что ты сделал что бы оно заработало?

**Comment by lil2kki** [comment]
в описании релиза написано

**Comment by viralgmd** [comment]
Понял

**Comment by lil2kki** [comment]
мод теперь хукает функцию fadeInMusic, что видимо более безопасно

**Comment by lil2kki** [comment]
закрываю значит

**Comment by viralgmd** [comment]
Да
